package it.meucci.utils;

public enum Errors {
    COMMAND_NOT_RECOGNIZED,
    UNABLE_TO_CONNECT,
    WRONG_ARGS,
    ALREADY_CONNECTED,
    NOT_CONNECTED_YET,
    NAME_NOT_AVAILABLE,
    NEED_A_NAME,
    DEST_NOT_CORRECT,
}
